# Generated by Django 5.0.6 on 2024-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(max_length=10),
        ),
    ]
