# Generated by Django 5.0.6 on 2024-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_phoneno_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
