# Generated by Django 5.0.6 on 2024-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='none', upload_to='student_photos/'),
        ),
    ]
