# Generated by Django 5.0.6 on 2024-06-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
