# Generated by Django 4.0.3 on 2022-03-10 12:19

from django.db import migrations, models
import ourapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to=ourapp.models.get_upload_path)),
            ],
        ),
    ]
