# Generated by Django 4.0.3 on 2022-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
