# Generated by Django 4.0.3 on 2022-03-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_student_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='present',
            new_name='is_present',
        ),
    ]
