# Generated by Django 4.0.3 on 2022-03-17 04:08

from django.db import migrations, models
import django.db.models.deletion
import ourapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=255)),
                ('image_field', models.FileField(blank=True, upload_to=ourapp.models.get_upload_path)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.student')),
            ],
        ),
    ]
