# Generated by Django 4.0.3 on 2022-03-17 04:27

from django.db import migrations, models
import ourapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0005_imageform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageform',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='imageform',
            name='image_field',
            field=models.FileField(upload_to=ourapp.models.get_upload_paths),
        ),
    ]
