# Generated by Django 5.0.6 on 2024-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0006_remove_imageform_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageform',
            name='roll_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
