# Generated by Django 5.0.6 on 2024-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_imageform_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageform',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
