# Generated by Django 5.0.6 on 2024-07-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0008_alter_imageform_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('is_present', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='imageform',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
